name: Docker Image CI/CD

on:
  push:
    branches: ["dev", "main", "feature/**"]
  pull_request:
    branches: ["dev"]

jobs:
  # Логин в Docker Hub на builder
  login-docker-hub:
    runs-on: self-hosted
    labels: [builder]
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

  # Сборка и публикация Docker образа
  build-and-push:
    needs: login-docker-hub
    runs-on: self-hosted
    labels: [builder]
    steps:
      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USER }}/${{ github.event.environment.REPOSITORY }}
        run: |
          TAG="${{ github.ref_name }}-${{ github.run_number }}"
          echo "Building image: $IMAGE_NAME:$TAG"
          docker build -t $IMAGE_NAME:$TAG ./app
          docker push $IMAGE_NAME:$TAG
          docker rmi $IMAGE_NAME:$TAG

  # Деплой на dev
  deploy-dev:
    if: startsWith(github.ref, 'refs/heads/dev') || startsWith(github.ref, 'refs/heads/feature/')
    runs-on: self-hosted
    labels: [dev]
    environment: DEV
    needs: build-and-push
    steps:
      - name: Deploy Application to DEV
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USER }}/${{ github.event.environment.REPOSITORY }}
        run: |
          TAG="${{ github.ref_name }}-${{ github.run_number }}"
          echo "Deploying image: $IMAGE_NAME:$TAG to DEV"
          docker rm -f app || true
          docker run -d -p 80:80 --name app $IMAGE_NAME:$TAG

  # Деплой на prod
  deploy-prod:
    if: startsWith(github.ref, 'refs/heads/main')
    runs-on: self-hosted
    labels: [prod]
    environment: PROD
    needs: build-and-push
    steps:
      - name: Deploy Application to PROD
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USER }}/${{ github.event.environment.REPOSITORY }}
        run: |
          TAG="${{ github.ref_name }}-${{ github.run_number }}"
          echo "Deploying image: $IMAGE_NAME:$TAG to PROD"
          docker rm -f app || true
          docker run -d -p 80:80 --name app $IMAGE_NAME:$TAG
